version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: eldendemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: gunicorn eldendemo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_SECRET_KEY: "django-insecure-CHANGE_ME"
      DJANGO_DEBUG: 'True'
      DJANGO_ALLOWED_HOSTS: '0.0.0.0,localhost'
      DATABASE_ENGINE: django.db.backends.postgresql
      POSTGRES_DB: eldendemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
