# Generated by Django 6.0.3 on 2026-03-21 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('founded_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=1)),
                ('character_class', models.CharField(blank=True, max_length=100)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.guild')),
            ],
        ),
    ]
