# Generated by Django 6.0.3 on 2026-03-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EldenBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('health', models.PositiveIntegerField(default=0)),
                ('rewards', models.TextField(blank=True, help_text='Recompensas separadas por vírgula')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Chefe Elden Ring',
                'verbose_name_plural': 'Chefes Elden Ring',
            },
        ),
        migrations.CreateModel(
            name='EldenCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Personagem Elden Ring',
                'verbose_name_plural': 'Personagens Elden Ring',
            },
        ),
        migrations.CreateModel(
            name='EldenWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weapon_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('physical_attack', models.PositiveIntegerField(default=0)),
                ('magic_attack', models.PositiveIntegerField(default=0)),
                ('fire_attack', models.PositiveIntegerField(default=0)),
                ('lightning_attack', models.PositiveIntegerField(default=0)),
                ('holy_attack', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Arma Elden Ring',
                'verbose_name_plural': 'Armas Elden Ring',
            },
        ),
    ]
