# Generated by Django 6.0.3 on 2026-03-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eldenboss_eldencharacter_eldenweapon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Guild',
        ),
    ]
